# Generated by Django 6.0.7 on 2026-07-23 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folders', '0001_initial'),
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider_file_id', models.CharField(max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=255)),
                ('web_view_link', models.URLField(blank=True, max_length=1024, null=True)),
                ('is_trashed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='folders.folder')),
                ('storage_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='storage.storageaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'folder', 'user')},
            },
        ),
    ]
