# Generated by Django 6.0.7 on 2026-07-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
