# Generated by Django 6.0.7 on 2026-08-02 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_checksum_file_is_favorite'),
        ('folders', '0005_folder_folders_fol_user_id_10fb22_idx'),
        ('storage', '0005_activitylog_storage_act_user_id_c3ba32_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['user', 'folder', 'is_trashed'], name='files_file_user_id_d9cc44_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['user', 'is_favorite', 'is_trashed'], name='files_file_user_id_c7f2e6_idx'),
        ),
    ]
