# Generated by Django 6.0.7 on 2026-07-23 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='storageaccount',
            old_name='access_token',
            new_name='encrypted_access_token',
        ),
        migrations.RenameField(
            model_name='storageaccount',
            old_name='refresh_token',
            new_name='encrypted_refresh_token',
        ),
        migrations.RenameField(
            model_name='storageaccount',
            old_name='email',
            new_name='provider_email',
        ),
        migrations.AlterUniqueTogether(
            name='storageaccount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='storageaccount',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('quota_full', 'Quota Full'), ('unauthorized', 'Unauthorized'), ('expired_token', 'Expired Token'), ('rate_limited', 'Rate Limited'), ('disconnected', 'Disconnected'), ('syncing', 'Syncing'), ('offline', 'Offline')], default='healthy', max_length=50),
        ),
        migrations.AddField(
            model_name='storageaccount',
            name='last_sync',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storageaccount',
            name='nickname',
            field=models.CharField(default='My Cloud Storage', max_length=255),
        ),
        migrations.AddField(
            model_name='storageaccount',
            name='provider_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storageaccount',
            name='provider',
            field=models.CharField(choices=[('google', 'Google Drive'), ('dropbox', 'Dropbox'), ('onedrive', 'OneDrive'), ('s3', 'Amazon S3')], default='google', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='storageaccount',
            unique_together={('user', 'provider_email', 'provider')},
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'File Uploaded'), ('delete', 'File Deleted'), ('connect', 'Drive Connected'), ('disconnect', 'Drive Disconnected'), ('sync', 'Quota Refreshed')], max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
