# Generated by Django 6.0.7 on 2026-07-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_rename_access_token_storageaccount_encrypted_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageaccount',
            name='workspace_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
