# Generated by Django 6.0.7 on 2026-07-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_storageaccount_workspace_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='new_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='old_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storageaccount',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('upload', 'File Uploaded'), ('download', 'File Downloaded'), ('rename', 'Item Renamed'), ('move', 'Item Moved'), ('copy', 'Item Copied'), ('delete', 'Item Soft Deleted'), ('restore', 'Item Restored'), ('permanent_delete', 'Item Permanently Deleted'), ('connect', 'Drive Connected'), ('disconnect', 'Drive Disconnected'), ('sync', 'Quota Refreshed')], max_length=50),
        ),
    ]
