# Generated by Django 6.0.7 on 2026-08-02 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_activitylog_ip_address_activitylog_new_path_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-timestamp'], name='storage_act_user_id_c3ba32_idx'),
        ),
    ]
