# Generated by Django 6.0.7 on 2026-07-25 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
        ('storage', '0003_storageaccount_workspace_folder_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_folder_id', models.CharField(max_length=255)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_mappings', to='folders.folder')),
                ('storage_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_mappings', to='storage.storageaccount')),
            ],
            options={
                'unique_together': {('folder', 'storage_account')},
            },
        ),
    ]
