# Generated by Django 6.0.7 on 2026-07-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_storagefolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
