# Generated by Django 6.0.7 on 2026-07-25 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0003_folder_is_trashed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public'), ('team', 'Team')], default='private', max_length=20),
        ),
    ]
