# Generated by Django 6.0.7 on 2026-08-02 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0004_folder_created_by_folder_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['user', 'parent', 'is_trashed'], name='folders_fol_user_id_10fb22_idx'),
        ),
    ]
